### ISSUE TITLE
需要字符串作为左操作数，而不是int（TypeError: 'in <string>' requires string as left operand, not int）

### ISSUE THREAD

**Issue by Zwc84** [bingqiu456/nonebot-plugin-covid-19-by#4]
我有预感这是一个非常简单的问题不过还是麻烦了。我什么都不会，寄

covid_19_by_group=[群号] #开启插件的群号 注意不要加""符号！！！

covid_19_by_colour=#ff4500 #设置文字转图片的颜色 如:#ffffff

covid_19_by_size=25 #设置文字转图片的大小 如:30

covid_19_by_images=[群号]#开启文字转图片的群 注意不要加""符号！！！

[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_covid_19_by) failed.
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_covid_19_by\__init__.py", line 42, in _
    if int(event.group_id) in group_covid:
TypeError: 'in <string>' requires string as left operand, not int

**Comment by AHBYCR** [comment]
同样的错误....

**Comment by bingqiu456** [comment]
学业忙 抱歉 `今周周末修复`
